from enum import Enum


class Severity(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"


class IssueType(str, Enum):
    RATE_MISMATCH = "RATE_MISMATCH"
    QUANTITY_MISMATCH = "QUANTITY_MISMATCH"
    EXPECTED_VS_BILLED_DIFFERENCE = "EXPECTED_VS_BILLED_DIFFERENCE"
    DISCOUNT_MISMATCH = "DISCOUNT_MISMATCH"
    CURRENCY_MISMATCH = "CURRENCY_MISMATCH"
    DUPLICATE_ENTRY = "DUPLICATE_ENTRY"
    MANUAL_OVERRIDE_ERROR = "MANUAL_OVERRIDE_ERROR"
    NEGATIVE_PRICING = "NEGATIVE_PRICING"
    ZERO_BILLING = "ZERO_BILLING"
    MISSING_CONTRACT_RATE = "MISSING_CONTRACT_RATE"
    TAX_MISMATCH = "TAX_MISMATCH"
    TIER_PRICING_MISMATCH = "TIER_PRICING_MISMATCH"
    OUT_OF_CONTRACT_BILLING = "OUT_OF_CONTRACT_BILLING"

